# Generated by Django 6.0.2 on 2026-02-14 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='status',
            field=models.CharField(choices=[('Reservado', 'Reserved'), ('Confirmado', 'Comfirmed'), ('Cancelado', 'Cancelled')], default='Reservado', max_length=20),
        ),
    ]
